# Generated by Django 5.2.3 on 2025-06-21 18:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Gamebook',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.SlugField(unique=True)),
                ('title', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Paragraph',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.IntegerField()),
                ('text', models.TextField()),
                ('combat_enemy', models.CharField(blank=True, max_length=100, null=True)),
                ('combat_skill', models.IntegerField(blank=True, null=True)),
                ('combat_stamina', models.IntegerField(blank=True, null=True)),
                ('gamebook', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='paragraphs', to='gamebooks.gamebook')),
            ],
            options={
                'unique_together': {('gamebook', 'number')},
            },
        ),
        migrations.CreateModel(
            name='Choice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(max_length=300)),
                ('target', models.IntegerField()),
                ('paragraph', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='choices', to='gamebooks.paragraph')),
            ],
        ),
    ]
