# Generated by Django 5.2.3 on 2025-06-22 20:07

import django.db.models.deletion
import django_ckeditor_5.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Gamebook',
            fields=[
                ('code', models.SlugField(max_length=100, primary_key=True, serialize=False, unique=True)),
                ('title', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Paragraph',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.IntegerField()),
                ('text', django_ckeditor_5.fields.CKEditor5Field(verbose_name='Texto do Parágrafo')),
                ('combat_enemy', models.CharField(blank=True, max_length=100, null=True)),
                ('combat_skill', models.IntegerField(blank=True, null=True)),
                ('combat_stamina', models.IntegerField(blank=True, null=True)),
                ('gamebook', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='paragraphs', to='gamebooks.gamebook')),
            ],
            options={
                'unique_together': {('gamebook', 'number')},
            },
        ),
        migrations.CreateModel(
            name='ReadingSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('state', models.JSONField(blank=True, default=dict)),
                ('book', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sessions', to='gamebooks.gamebook')),
                ('current_paragraph', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='gamebooks.paragraph')),
            ],
        ),
    ]
