# Generated by Django 5.2.3 on 2025-06-23 21:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gamebooks', '0002_readingsession_history'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='paragraph',
            name='combat_enemy',
        ),
        migrations.RemoveField(
            model_name='paragraph',
            name='combat_skill',
        ),
        migrations.RemoveField(
            model_name='paragraph',
            name='combat_stamina',
        ),
        migrations.AddField(
            model_name='paragraph',
            name='events',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
