# Generated by Django 5.2.3 on 2025-06-23 23:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gamebooks', '0003_remove_paragraph_combat_enemy_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReadingSessionState',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('paragraph_number', models.IntegerField()),
                ('state', models.JSONField(default=dict)),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='state_snapshots', to='gamebooks.readingsession')),
            ],
            options={
                'ordering': ['created_at'],
            },
        ),
    ]
